# app engine config file

runtime: php74

env_variables:
  CLOUDSQL_CONNECTION_NAME: $CLOUDSQL_CONNECTION_NAME
  CLOUDSQL_USER: $CLOUDSQL_USER
  CLOUDSQL_PASSWORD: $CLOUDSQL_PASSWORD
  CLOUDSQL_DATABASE_NAME: $CLOUDSQL_DATABASE_NAME
  
  AUTH0_CLIENT_ID: $AUTH0_CLIENT_ID

  AUTH0_DOMAIN: $AUTH0_DOMAIN

  AUTH0_CLIENT_SECRET: $AUTH0_CLIENT_SECRET

  AUTH0_REDIRECT_URI: $AUTH0_REDIRECT_URI

  AUTH0_LOGOUT_URI: $AUTH0_LOGOUT_URI

  HOSTNAME:  $HOSTNAME
  USERNAME:  $USERNAME
  PASSWORD:  $PASSWORD
  DATABASE:  $DATABASE

  # admin role
  ADMIN: $ADMIN

  # cloud storage config  
  BUCKETNAME: $BUCKETNAME
  CLOUD_STORAGE_CONFIG_FILE: $CLOUD_STORAGE_CONFIG_FILE
  PROJECT_ID: $PROJECT_ID


handlers:
  - url: /assets
    static_dir: assets
  - url: /media-dir
    static_dir: media-dir
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto    
