# app engine config file

runtime: php74

env_variables:

  CLOUDSQL_CONNECTION_NAME: $CLOUDSQL_CONNECTION_NAME
  CLOUDSQL_USER: $CLOUDSQL_USER
  CLOUDSQL_PASSWORD: $CLOUDSQL_PASSWORD
  CLOUDSQL_DATABASE_NAME: $CLOUDSQL_DATABASE_NAME

handlers:
  - url: /assets
    static_dir: assets
  - url: /media-dir
    static_dir: media-dir
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto    
