name: Deploy to GAE
on: push

jobs: 
  deploy: 
    name: deploying to Google cloud
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: create env 
        env: 
          ADMIN: ${{ secrets.ADMIN }}
          AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
          AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
          AUTH0_COOKIE_SECRET: ${{ secrets.AUTH0_COOKIE_SECRET }}
          AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
          AUTH0_LOGOUT_URI: ${{ secrets.AUTH0_LOGOUT_URI }}
          AUTH0_REDIRECT_URI: ${{ secrets.AUTH0_REDIRECT_URI }}
          BUCKETNAME: ${{ secrets.BUCKETNAME }}
          CLOUDSQL_CONNECTION_NAME: ${{ secrets.CLOUDSQL_CONNECTION_NAME }}
          CLOUDSQL_DATABASE_NAME: ${{ secrets.CLOUDSQL_DATABASE_NAME }}
          CLOUDSQL_PASSWORD: ${{ secrets.CLOUDSQL_PASSWORD }}
          CLOUDSQL_USER: ${{ secrets.CLOUDSQL_USER }}
          CLOUD_STORAGE_CONFIG_FILE: ${{ secrets.CLOUD_STORAGE_CONFIG_FILE }}
          DATABASE: ${{ secrets.DATABASE }}
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
          GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
          HOSTNAME: ${{ secrets.HOSTNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          USERNAME: ${{ secrets.USERNAME }}
        run: |
          touch .env
          echo ${{ secrets.ADMIN }} >> .env
          cat .env
      # - name: Deploy
      #   id: deploy
      #   uses: google-github-actions/deploy-appengine@v0.2.0
      #   with: 
      #     deliverables: app.yaml
      #     project_id: ${{ secrets.GCP_PROJECT }}
      #     credentials: ${{ secrets.GCP_CREDENTIALS }}